IPAMFunction:
  Type: AWS::Lambda::Function
  Properties:
    Code:
      S3Bucket: `<bucket-name>`
      S3Key:`ipam_lambda.zip`
  Handler: `ipan_lambda.lambda_handler`
  Runtime: Python 2.7
  Timeout:10
  
#
IpamAPI:
Type:"Custom::CIDRs"
Properties:
ServiceToken:!Getatt IPAMFunction.Arn
subnet_id: ??
mask: !Ref `VpcMask`
  
